using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Bundle.Client.Palettes
{
    public class PacketPalette1162 : PacketTypePalette
    {
        private Dictionary<int, PacketTypeIn> typeIn = new Dictionary<int, PacketTypeIn>()
        {
            { 0x00, PacketTypeIn.SpawnEntity },
            { 0x01, PacketTypeIn.SpawnExperienceOrb },
            { 0x02, PacketTypeIn.SpawnLivingEntity },
            { 0x03, PacketTypeIn.SpawnPainting },
            { 0x04, PacketTypeIn.SpawnPlayer },
            { 0x05, PacketTypeIn.EntityAnimation },
            { 0x06, PacketTypeIn.Statistics },
            { 0x07, PacketTypeIn.AcknowledgePlayerDigging },
            { 0x08, PacketTypeIn.BlockBreakAnimation },
            { 0x09, PacketTypeIn.BlockEntityData },
            { 0x0A, PacketTypeIn.BlockAction },
            { 0x0B, PacketTypeIn.BlockChange },
            { 0x0C, PacketTypeIn.BossBar },
            { 0x0D, PacketTypeIn.ServerDifficulty },
            { 0x0E, PacketTypeIn.ChatMessage },
            { 0x0F, PacketTypeIn.TabComplete },
            { 0x10, PacketTypeIn.DeclareCommands },
            { 0x11, PacketTypeIn.WindowConfirmation },
            { 0x12, PacketTypeIn.CloseWindow },
            { 0x13, PacketTypeIn.WindowItems },
            { 0x14, PacketTypeIn.WindowProperty },
            { 0x15, PacketTypeIn.SetSlot },
            { 0x16, PacketTypeIn.SetCooldown },
            { 0x17, PacketTypeIn.PluginMessage },
            { 0x18, PacketTypeIn.NamedSoundEffect },
            { 0x19, PacketTypeIn.Disconnect },
            { 0x1A, PacketTypeIn.EntityStatus },
            { 0x1B, PacketTypeIn.Explosion },
            { 0x1C, PacketTypeIn.UnloadChunk },
            { 0x1D, PacketTypeIn.ChangeGameState },
            { 0x1E, PacketTypeIn.OpenHorseWindow },
            { 0x1F, PacketTypeIn.KeepAlive },
            { 0x20, PacketTypeIn.ChunkData },
            { 0x21, PacketTypeIn.Effect },
            { 0x22, PacketTypeIn.Particle },
            { 0x23, PacketTypeIn.UpdateLight },
            { 0x24, PacketTypeIn.JoinGame },
            { 0x25, PacketTypeIn.MapData },
            { 0x26, PacketTypeIn.TradeList },
            { 0x27, PacketTypeIn.EntityPosition },
            { 0x28, PacketTypeIn.EntityPositionAndRotation },
            { 0x29, PacketTypeIn.EntityRotation },
            { 0x2A, PacketTypeIn.EntityMovement },
            { 0x2B, PacketTypeIn.VehicleMove },
            { 0x2C, PacketTypeIn.OpenBook },
            { 0x2D, PacketTypeIn.OpenWindow },
            { 0x2E, PacketTypeIn.OpenSignEditor },
            { 0x2F, PacketTypeIn.CraftRecipeResponse },
            { 0x30, PacketTypeIn.PlayerAbilities },
            { 0x31, PacketTypeIn.CombatEvent },
            { 0x32, PacketTypeIn.PlayerInfo },
            { 0x33, PacketTypeIn.FacePlayer },
            { 0x34, PacketTypeIn.PlayerPositionAndLook },
            { 0x35, PacketTypeIn.UnlockRecipes },
            { 0x36, PacketTypeIn.DestroyEntities },
            { 0x37, PacketTypeIn.RemoveEntityEffect },
            { 0x38, PacketTypeIn.ResourcePackSend },
            { 0x39, PacketTypeIn.Respawn },
            { 0x3A, PacketTypeIn.EntityHeadLook },
            { 0x3B, PacketTypeIn.MultiBlockChange },
            { 0x3C, PacketTypeIn.SelectAdvancementTab },
            { 0x3D, PacketTypeIn.WorldBorder },
            { 0x3E, PacketTypeIn.Camera },
            { 0x3F, PacketTypeIn.HeldItemChange },
            { 0x40, PacketTypeIn.UpdateViewPosition },
            { 0x41, PacketTypeIn.UpdateViewDistance },
            { 0x42, PacketTypeIn.SpawnPosition },
            { 0x43, PacketTypeIn.DisplayScoreboard },
            { 0x44, PacketTypeIn.EntityMetadata },
            { 0x45, PacketTypeIn.AttachEntity },
            { 0x46, PacketTypeIn.EntityVelocity },
            { 0x47, PacketTypeIn.EntityEquipment },
            { 0x48, PacketTypeIn.SetExperience },
            { 0x49, PacketTypeIn.UpdateHealth },
            { 0x4A, PacketTypeIn.ScoreboardObjective },
            { 0x4B, PacketTypeIn.SetPassengers },
            { 0x4C, PacketTypeIn.Teams },
            { 0x4D, PacketTypeIn.UpdateScore },
            { 0x4E, PacketTypeIn.TimeUpdate },
            { 0x4F, PacketTypeIn.Title },
            { 0x50, PacketTypeIn.EntitySoundEffect },
            { 0x51, PacketTypeIn.SoundEffect },
            { 0x52, PacketTypeIn.StopSound },
            { 0x53, PacketTypeIn.PlayerListHeaderAndFooter },
            { 0x54, PacketTypeIn.NBTQueryResponse },
            { 0x55, PacketTypeIn.CollectItem },
            { 0x56, PacketTypeIn.EntityTeleport },
            { 0x57, PacketTypeIn.Advancements },
            { 0x58, PacketTypeIn.EntityProperties },
            { 0x59, PacketTypeIn.EntityEffect },
            { 0x5A, PacketTypeIn.DeclareRecipes },
            { 0x5B, PacketTypeIn.Tags },
        };

        private Dictionary<int, PacketTypeOut> typeOut = new Dictionary<int, PacketTypeOut>()
        {
            { 0x00, PacketTypeOut.TeleportConfirm },
            { 0x01, PacketTypeOut.QueryBlockNBT },
            { 0x02, PacketTypeOut.SetDifficulty },
            { 0x03, PacketTypeOut.ChatMessage },
            { 0x04, PacketTypeOut.ClientStatus },
            { 0x05, PacketTypeOut.ClientSettings },
            { 0x06, PacketTypeOut.TabComplete },
            { 0x07, PacketTypeOut.WindowConfirmation },
            { 0x08, PacketTypeOut.ClickWindowButton },
            { 0x09, PacketTypeOut.ClickWindow },
            { 0x0A, PacketTypeOut.CloseWindow },
            { 0x0B, PacketTypeOut.PluginMessage },
            { 0x0C, PacketTypeOut.EditBook },
            { 0x0D, PacketTypeOut.EntityNBTRequest },
            { 0x0E, PacketTypeOut.InteractEntity },
            { 0x0F, PacketTypeOut.GenerateStructure },
            { 0x10, PacketTypeOut.KeepAlive },
            { 0x11, PacketTypeOut.LockDifficulty },
            { 0x12, PacketTypeOut.PlayerPosition },
            { 0x13, PacketTypeOut.PlayerPositionAndRotation },
            { 0x14, PacketTypeOut.PlayerRotation },
            { 0x15, PacketTypeOut.PlayerMovement },
            { 0x16, PacketTypeOut.VehicleMove },
            { 0x17, PacketTypeOut.SteerBoat },
            { 0x18, PacketTypeOut.PickItem },
            { 0x19, PacketTypeOut.CraftRecipeRequest },
            { 0x1A, PacketTypeOut.PlayerAbilities },
            { 0x1B, PacketTypeOut.PlayerDigging },
            { 0x1C, PacketTypeOut.EntityAction },
            { 0x1D, PacketTypeOut.SteerVehicle },
            { 0x1E, PacketTypeOut.SetDisplayedRecipe },
            { 0x1F, PacketTypeOut.SetRecipeBookState },
            { 0x20, PacketTypeOut.NameItem },
            { 0x21, PacketTypeOut.ResourcePackStatus },
            { 0x22, PacketTypeOut.AdvancementTab },
            { 0x23, PacketTypeOut.SelectTrade },
            { 0x24, PacketTypeOut.SetBeaconEffect },
            { 0x25, PacketTypeOut.HeldItemChange },
            { 0x26, PacketTypeOut.UpdateCommandBlock },
            { 0x27, PacketTypeOut.UpdateCommandBlockMinecart },
            { 0x28, PacketTypeOut.CreativeInventoryAction },
            { 0x29, PacketTypeOut.UpdateJigsawBlock },
            { 0x2A, PacketTypeOut.UpdateStructureBlock },
            { 0x2B, PacketTypeOut.UpdateSign },
            { 0x2C, PacketTypeOut.Animation },
            { 0x2D, PacketTypeOut.Spectate },
            { 0x2E, PacketTypeOut.PlayerBlockPlacement },
            { 0x2F, PacketTypeOut.UseItem },
        };

        protected override Dictionary<int, PacketTypeIn> GetListIn()
        {
            return typeIn;
        }

        protected override Dictionary<int, PacketTypeOut> GetListOut()
        {
            return typeOut;
        }
    }
}
